name: Telega Trigger

on:
  issue_comment:
    types: [created]

jobs:
  triggerTelega:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && github.event.comment.body == '/telega'

    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0

    - name: Set up JAVA
      uses: actions/setup-java@v3.6.0
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        cache: 'gradle'
        check-latest: true

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Cache Gradle packages
      uses: actions/cache@v3.0.11
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Test
      run: ./gradlew test
    - name: Assemble
      run: ./gradlew assembleDebug -Dec_accessToken="${{ secrets.EC_TOKEN }}" -Dmetrica_api="${{ secrets.METRICA_API }}"
      
    - name: Cleanup Gradle Cache
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties

    - name: Get APK
      uses: actions/upload-artifact@v3.1.1
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
          
    - name: Get wearos APK
      uses: actions/upload-artifact@v3.1.1
      with:
        name: wearos-debug
        path: wearos/build/outputs/apk/debug/wearos-debug.apk

    - name: Send apk to telegram
      env: 
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      if: github.event_name == 'pull_request' && env.TELEGRAM_TOKEN != ''
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: env.TELEGRAM_TOKEN
        message: |
          ${{ github.event.pull_request.title }}
          ${{ github.base_ref }} <= ${{ github.head_ref }}
          PR: https://github.com/Wheellog/Wheellog.Android/pull/${{github.event.number}}
        document: app/build/outputs/apk/debug/app-debug.apk
